### ISSUE TITLE
Exit code is 13

### ISSUE THREAD

**Issue by nickserv** [nickmccurdy/cacheinfo#7]
Expected exit code 0, but actually received:

> `13` **Unfinished Top-Level Await**: `await` was used outside of a function in the top-level code, but the passed `Promise` never resolved.

https://nodejs.org/api/process.html#exit-codes

**Comment by nickmccurdy** [comment]
> `13` **Unfinished Top-Level Await**: `await` was used outside of a function in the top-level code, but the passed `Promise` never resolved.

**Comment by nickserv** [comment]
This is happening again as of 10411fcffaed5e279045833478b13804b5adfed6. I think the `ReadableStream`'s error handling is tripping and not closing the controller.
